### ISSUE TITLE
Don't find Race code 

### ISSUE THREAD

**Issue by thomaslprr** [ParsaD23/MotoGP-API#1]
Hello, first of all I wanted to congratulate you for your work! 

I am doing this issue because I can't find the race codes in the HTML source code of the pages. 
Can you send me the URL of a page of one of the circuits where it can be found so that I understand the logic? 

Where can I find the code of the circuit of Jerez for example? 

Thanks a lot!
Thomas

**Comment by thomaslprr** [comment]
### Race code values :
**QAT** : Barwa Grand Prix of Qatar
**DOH** : TISSOT Grand Prix of Doha
**POR** : Grande Prémio 888 de Portugal
**ESP** : Gran Premio Red Bull de España
**FRA** : SHARK Grand Prix de France
**ITA** : Gran Premio d'Italia
**CAT** : Gran Premi di Catalunya
**DEU** : Motorrad Grand Prix Deutschland
**NLD** : TT Assen
**FIN** : Grand Prix of Finland
**AUT** : Motorrad Grand Prix von Österreich
**GBR** : British Grand Prix
**ARA** : Gran Premio de Aragón
**SMR** : Gran Premio di San Marino e della Riviera di Rimini
**JAP** : Grand Prix of Japan
**THA** : Thailand Grand Prix
**AUS** : Australian Motorcycle Grand Prix
**MYS** : Malaysia Motorcycle Grand Prix
**VAL** : Gran Premio de la Comunitat Valenciana

I think it can be useful !

**Comment by ParsaD23** [comment]
Hi,

Thanks a lot for your feedback. I really appreciate it! 

The codes can be found by looking in the riders' or teams' standings at this [link](https://results.motorsportstats.com/series/motogp). I will change the wiki in order to explicitly indicate it.

However, I highly suggest to check the website for every season you are interested in because I noticed that they are often inconsistent with the code assignments (the same grand prix sometimes has different racecodes for different seasons or in the 2003 season they used the same code for the suzuka and the motegi grand prix). For this reason, I've also added the option to pass as a parameter the race number instead of the race code.

Thanks a lot for reporting the issue!
